version: '3.9'

services:
  abc-server:
    image: nginx:1.21.1
    container_name: nginx-abc
    ports:
      - 80:80
    networks:
      - net-abc
    volumes:
      - ./confs/servers:/etc/nginx/conf.d/
      - ./ecommerce-abc:/var/www/html

  abc-app:
    build: ./ecommerce-abc
    container_name: ecommerce-abc
    networks:
      - net-abc
    volumes:
      - ./ecommerce-abc:/var/www/html

  mysql-abc:
    image: mysql:5.7
    container_name: mysql-abc
    volumes: 
      - ./confs/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - 3306:3306
    networks: 
      - net-abc

networks: 
  net-abc:
    driver: bridge
